site_name: ENote

site_url: https://olexsyn.github.io/enote

repo_url:  https://github.com/olexsyn/enote
repo_name: olexsyn/enote
edit_uri:  edit/master/docs/                  # шлях у репозиторії до директорії docs/

plugins:
  - search
  - tags

theme:
  name: material
  language: uk
  favicon: assets/images/favicon.png
  logo: assets/images/enote_logo.png
  features:
    - navigation.indexes        # ! видаляє дублікат і робить пункт посиланням в сайдбарі, коли в nav посилання стоїть на другому рядку https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.sections
    - navigation.tabs           # вмикає горизонтальні вкладки
    - navigation.top
    - navigation.tabs.sticky    # необов'язково, робить їх "липкими" що це?
    - navigation.path
    - header.autohide
    - content.action.view       # увімкнути "View source"
    - content.action.edit       # увімкнути "Edit this page"
    - content.code.copy         # копіювати код
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

# extra_css:
#   - stylesheets/extra.css

nav:
  - Home: index.md
  - Linux:                      # якщо активне гор.меню і пункт не має index.md - відкриється наступна за цим сторінка
    - Commands:
      - history:     linux/commands/history.md
      - htpasswd:    linux/commands/htpasswd.md
    - Ubuntu Server:
      - Setup: linux/ubuntu-server/setup.md
      - Usage:
        - Basics: linux/ubuntu-server/usage/basics.md
        - Advanced:
          - Tips: linux/ubuntu-server/usage/advanced/tips.md
          - Examples: linux/ubuntu-server/usage/advanced/examples.md
  - Python:
    - python/index.md
    - Virtual environment: python/venv/index.md
  - JavaScript:
    - javascript/index.md
  - MariaDB:
    - mariadb/index.md
  - Setup: setup.md
  - Tags: tags.md
